FROM hongccc/sglang-omni@sha256:6a8f60af7ca868dc266c118249d12fc73ba85e2e8075e5e31473bd25d349acfa

ENV TRITON_LIBCUDA_PATH="/usr/lib/x86_64-linux-gnu"

RUN apt-get update \
    && apt-get install -y --no-install-recommends sox \
    && ln -sfn libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
        accelerate==1.14.0 \
        hydra-core==1.3.4 \
        jiwer==4.0.0 \
        librosa==0.11.0 \
        "mistral_common[audio]==1.11.2" \
        modelscope==1.37.1 \
        msgpack==1.2.1 \
        numba==0.63.1 \
        onnxruntime==1.28.0 \
        pytest-asyncio==1.4.0 \
        qwen-vl-utils==0.0.11 \
        silero-vad==6.2.1 \
        socksio==1.0.0 \
        websockets==16.1.1 \
        x-transformers==2.24.0 \
        zhon==2.1.1 \
    && pip install --no-cache-dir \
        descript-audio-codec==1.0.0 \
        descript-audiotools==0.7.2 \
    && pip install --no-cache-dir --no-deps qwen-tts==0.1.1 \
    && pip install --no-cache-dir "protobuf>=6.31.1,<7"

WORKDIR /opt/sglang-omni
COPY . .
RUN pip install --no-cache-dir --no-deps -e .
